### ISSUE TITLE
Nil pointer exception when fetching storage servers

### ISSUE THREAD

**Issue by JoshuaMcManus** [FoundationDB/fdb-kubernetes-operator#456]
The operator entered a crash loop when trying to iterate over a list of containers in a pod. The pertinent line of code can be found here: https://github.com/FoundationDB/fdb-kubernetes-operator/blob/bf7f8844a2a9a65dff385a527e7315fdd90cdffd/controllers/pod_models.go#L1227-L1236

Here is the entire stack trace:
```
E0113 20:55:41.125922       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 615 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x148e460, 0x22a7340)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x148e460, 0x22a7340)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/FoundationDB/fdb-kubernetes-operator/controllers.getStorageServersPerPodForPod(0x0, 0xc0019f2f30, 0x1647661, 0xf)
	/go/pkg/mod/github.com/!foundation!d!b/fdb-kubernetes-operator@v0.25.1/controllers/pod_models.go:1230 +0x3a
github.com/FoundationDB/fdb-kubernetes-operator/controllers.getStorageServersPerPodForInstance(...)
	/go/pkg/mod/github.com/!foundation!d!b/fdb-kubernetes-operator@v0.25.1/controllers/pod_models.go:1224
github.com/FoundationDB/fdb-kubernetes-operator/controllers.UpdateStatus.Reconcile(0xc0007f2ab0, 0x1863fa0, 0xc000106210, 0xc001d44800, 0x3000100, 0x0, 0x0)
	/go/pkg/mod/github.com/!foundation!d!b/fdb-kubernetes-operator@v0.25.1/controllers/update_status.go:147 +0x2211
github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBClusterReconciler).Reconcile(0xc0007f2ab0, 0xc003bcb710, 0xa, 0xc0038a3240, 0x17, 0xc0030bbc00, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/!foundation!d!b/fdb-kubernetes-operator@v0.25.1/controllers/cluster_controller.go:145 +0x61b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ec900, 0x14dea00, 0xc0017f0aa0, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ec900, 0x10e1a00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001ec900)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00422ac40)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00422ac40, 0x3b9aca00, 0x0, 0xc0004fbb01, 0xc000600120)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00422ac40, 0x3b9aca00, 0xc000600120)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x328
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x130caea]
goroutine 615 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x148e460, 0x22a7340)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/FoundationDB/fdb-kubernetes-operator/controllers.getStorageServersPerPodForPod(0x0, 0xc0019f2f30, 0x1647661, 0xf)
	/go/pkg/mod/github.com/!foundation!d!b/fdb-kubernetes-operator@v0.25.1/controllers/pod_models.go:1230 +0x3a
github.com/FoundationDB/fdb-kubernetes-operator/controllers.getStorageServersPerPodForInstance(...)
	/go/pkg/mod/github.com/!foundation!d!b/fdb-kubernetes-operator@v0.25.1/controllers/pod_models.go:1224
github.com/FoundationDB/fdb-kubernetes-operator/controllers.UpdateStatus.Reconcile(0xc0007f2ab0, 0x1863fa0, 0xc000106210, 0xc001d44800, 0x3000100, 0x0, 0x0)
	/go/pkg/mod/github.com/!foundation!d!b/fdb-kubernetes-operator@v0.25.1/controllers/update_status.go:147 +0x2211
github.com/FoundationDB/fdb-kubernetes-operator/controllers.(*FoundationDBClusterReconciler).Reconcile(0xc0007f2ab0, 0xc003bcb710, 0xa, 0xc0038a3240, 0x17, 0xc0030bbc00, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/!foundation!d!b/fdb-kubernetes-operator@v0.25.1/controllers/cluster_controller.go:145 +0x61b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ec900, 0x14dea00, 0xc0017f0aa0, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ec900, 0x10e1a00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001ec900)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00422ac40)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00422ac40, 0x3b9aca00, 0x0, 0xc0004fbb01, 0xc000600120)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00422ac40, 0x3b9aca00, 0xc000600120)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x328
```

**Comment by johscheuer** [comment]
This is actually pretty strange because from the error message it seems like there are either no containers defined or the Pod is missing it's spec.

**Comment by johscheuer** [comment]
This bug was probably introduced in https://github.com/FoundationDB/fdb-kubernetes-operator/pull/409 I will create some additional tests and fix it. Thanks for reporting!
